### ISSUE TITLE
Error in schema: Could not dump table .. NoMethodError

### ISSUE THREAD

**Issue by ihinojal** [jruby/activerecord-jdbc-adapter#632]
I couldn't find a duplicated, and maybe its something you are aware to or is another gem what is causing this problem, but just in case..

**AR-JDBC's version used:** `1.3.15 (not tried master)`
**version of Rails / ActiveRecord you're running with:** `4.2.0/4.2.0`
**JRuby version (you might include your Java version as well)** -
`jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab OpenJDK 64-Bit Server VM 24.75-b04 on 1.7.0_75-b13 +jit [linux-amd64]`

**How to reproduce:**

    ivan@z11:~/Development$ rails new newapp -d=jdbcpostgresql

    (... configuring database conection in database.yml: username and password...)

    ivan@z11:~/Development/newapp$ rake db:create
    NOTE: ActiveRecord 4.2 is not (yet) fully supported by AR-JDBC, please help us finish 4.2 support -    check http://bit.ly/jruby-42 for starters

    ivan@z11:~/Development/newapp$ rails generate model post name:string
    NOTE: ActiveRecord 4.2 is not (yet) fully supported by AR-JDBC, please help us finish 4.2 support - check http://bit.ly/jruby-42 for starters
          invoke  active_record
          create    db/migrate/20150318084507_create_posts.rb
          create    app/models/post.rb
          invoke    test_unit
          create      test/models/post_test.rb
          create      test/fixtures/posts.yml

    ivan@z11:~/Development/newapp$ rake db:migrate
    NOTE: ActiveRecord 4.2 is not (yet) fully supported by AR-JDBC, please help us finish 4.2 support - check http://bit.ly/jruby-42 for starters
    == 20150318084507 CreatePosts: migrating ======================================
    -- create_table(:posts)
      -> 0.0197s
      -> 0 rows
    == 20150318084507 CreatePosts: migrated (0.0222s) =============================

    ivan@z11:~/Development/newapp$ tail db/schema.rb 
    ActiveRecord::Schema.define(version: 20150318084507) do
      # These are extensions that must be enabled in order to support this database
      enable_extension "plpgsql"
    # Could not dump table "posts" because of following NoMethodError
    #   undefined method `[]' for nil:NilClass
    end

Notes: 
 - It works fine in rails 4.1.x
 - The migrations in the database runs fine: 
```
    ivan@z11:~/Development/newapp$ psql -d newapp_development -c '\dt'
                List of relations
    Schema |       Name        | Type  | Owner 
    --------+-------------------+-------+-------
    public | posts             | table | ivan
    public | schema_migrations | table | ivan
    (2 rows)
```

**Comment by F2Andy** [comment]
I get this also, running on Rails version 4.2.0, with Ruby 1.9.3, on JRuby 1.7.19 (Java 1.7.0_60), on Windows. Worked for me on Rails 4.1 too.

**Comment by kares** [comment]
feel free to look into it ... that warning note won't just go away :) on it's own - let me know if you need help!

**Comment by simonykq** [comment]
I got this problem as well when upgrade rails to 4.2. My jruby version is 1.7.16

**Comment by anicholson** [comment]
I'm seeing this happen on a Sinatra app using version 4.2.

JRuby version: `jruby 1.7.19 (1.9.3p551) 2015-03-11 32f5af0 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17 +jit [darwin-x86_64]`

**Comment by anicholson** [comment]
Digging a little through the backtraces of the error, I discovered the error occurs [here:](https://github.com/jruby/activerecord-jdbc-adapter/blob/master/lib/arjdbc/postgresql/adapter.rb#L240)

```ruby
    # Adds `:array` option to the default set provided by the `AbstractAdapter`.
    def prepare_column_options(column, types)
      spec = super
      spec[:array] = 'true' if column.respond_to?(:array) && column.array
      spec[:default] = "\"#{column.default_function}\"" if column.default_function
      spec
    end if AR4_COMPAT
```

Following the `super` call into AR proper, the lines that blow up are [here:](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/abstract/schema_dumper.rb#L24)

```ruby

      # This can be overridden on a Adapter level basis to support other
      # extended datatypes (Example: Adding an array option in the
      # PostgreSQLAdapter)
      def prepare_column_options(column, types)
        spec = {}
        spec[:name]      = column.name.inspect
        spec[:type]      = column.type.to_s
        spec[:null]      = 'false' unless column.null

        # This is the line where the exception originates:
        limit = column.limit || types[column.type][:limit]
        spec[:limit]     = limit.inspect if limit
        spec[:precision] = column.precision.inspect if column.precision
        spec[:scale]     = column.scale.inspect if column.scale

        default = schema_default(column) if column.has_default?
        spec[:default]   = default unless default.nil?

        spec
      end
```

Interrogating `column` before that line executed showed that:

 ```ruby
column.limit    # => nil
column.type     # => nil
```

so, by extension:

```ruby

types[column.type][:limit]
# => types[nil][:limit]
# => nil[:limit]
# => NoMethodError: [] on nil

```

**Comment by anicholson** [comment]
@kares I know almost nothing about how the internals of AR work, so I don't know what I should do next. Help please? :)

**Comment by kares** [comment]
@anicholson this type of bugs are very specific I'm not sure I can be of any help ... I would proceed with finding out where the `types` are coming from - it's likely that we do not have the same type map as we never really needed it - AR-JDBC started "emulating" them for PG on 4.0/1 but than in 4.2 it's assumed more and more in the internals, so it might get a little messy or it might be a simply fix. you'll find out :)

**Comment by kares** [comment]
types under AR 4.2 should [now](https://github.com/jruby/activerecord-jdbc-adapter/commit/a0f1d1f46d380e8db28b52d08e37d0a22191346e) be fine on **1-3-stable** ... also the [test](https://github.com/jruby/activerecord-jdbc-adapter/commit/a67d58a3bad075a54b7a76c73a5d398d248e2171) is there, (hopefully) close to fixed!
